# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: todo_group_name
  joint_model_group_pose: todo_state_name
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
    - gripper_finger1_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: ""
    action_ns: /scaled_pos_joint_traj_controller/follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

shoulder_pan_controller:
  type: position_controllers/JointPositionController
  joint: shoulder_pan_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
shoulder_lift_controller:
  type: position_controllers/JointPositionController
  joint: shoulder_lift_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
elbow_controller:
  type: position_controllers/JointPositionController
  joint: elbow_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
wrist_1_controller:
  type: position_controllers/JointPositionController
  joint: wrist_1_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
wrist_2_controller:
  type: position_controllers/JointPositionController
  joint: wrist_2_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
wrist_3_controller:
  type: position_controllers/JointPositionController
  joint: wrist_3_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

# To control via Gazebo
# ur5_arm_controller:
#   type: position_controllers/JointTrajectoryController
#   joints:
#     - shoulder_pan_joint
#     - shoulder_lift_joint
#     - elbow_joint
#     - wrist_1_joint
#     - wrist_2_joint
#     - wrist_3_joint
#   gains:
#     shoulder_pan_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     shoulder_lift_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     elbow_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     wrist_1_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     wrist_2_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     wrist_3_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1