joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: &loop_hz 125

joint_group_vel_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint